//
// Created by thoma on 12/31/2025.
//

#ifndef STUDENT_RECORD_MANAGER_PROJECT_STUDENTMANAGER_H
#define STUDENT_RECORD_MANAGER_PROJECT_STUDENTMANAGER_H


class StudentManager {
};


#endif //STUDENT_RECORD_MANAGER_PROJECT_STUDENTMANAGER_H